version: "3.0"
services:
  wait:
    depends_on:
        - localstack
    image: waisbrot/wait
    environment:
      TARGETS: localstack:4569,localstack:4572
  localstack:
    image: localstack/localstack
    ports:
      - "61023:4569"
      - "61024:4572"
      # The UI
      - "61025:8080"
  node:
    build:
      context: ./
    image: aws-utils-test-image
    volumes:
      - ./:/home/node
    depends_on: 
      - localstack
    tty: true